# 生产环境配置文件
# @author Ayaka
#
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/loj
    username: root
    password: 123456
  # Redis 配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        password: 123456
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: 123456

